import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import ClientProvider from "@/components/ClientProvider";
import ProviderApollo from "@/components/ApolloProvider";
import TwitterLayout from "@/components/Layout/TwitterLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={process.env.GOOGLE_ID || ""}>
          <ProviderApollo>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <ClientProvider>
                <TwitterLayout>
                  {children}
                  <Toaster />
                </TwitterLayout>
              </ClientProvider>
            </ThemeProvider>
          </ProviderApollo>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
